version: '2'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
   app-timesheet:
     image: yassinemsadaa/skistation
     restart: on-failure
     environment:
       SPRING_APPLICATION_JSON: '{"spring.datasource.url:"jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true",
         "spring.datasource.username":"root",
         "spring.datasource.password":"root",
         "spring.jpa.hibernate.ddl-auto":"update",
         "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL5InnoDBDialect"}'
     ports:
       - 8089:8089
     stdin_open: true
     tty: true
     volumes:
       - ./app-data:/app/data
volumes:
  prom_data:
