version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE:
    ports:
      - "3306:3306"

  spring-app:
    build: "https://github.com/WassimB12/5SAE6_Wamya_SkyStation"
    ports:
      - "8080:8080"
    depends_on:
      - mysql
